name: OSX CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
            channels: conda-forge
            python-version: ${{ matrix.python-version }}

      - name: Show info about `base` environment
        shell: "bash -l {0}"
        run: |
          conda info
          conda config --show-sources
          conda list --show-channel-urls

      - name: Set up `env`
        shell: "bash -l {0}"
        run: >
          conda create -n env
          c-compiler cxx-compiler 'clang>=12.0.1'
          python=${{matrix.python-version}} wheel pip

      - name: Show info about `env` environment
        shell: "bash -l {0}"
        run: |
          conda list --show-channel-urls -n env

      - name: Install numcodecs
        shell: "bash -l {0}"
        run: |
          conda activate env
          export CC=clang
          python -m pip install -v -e .[test,msgpack,zfpy]

      - name: List installed packages
        shell: "bash -l {0}"
        run: |
          conda activate env
          python -m pip list

      - name: Run tests
        shell: "bash -l {0}"
        run: |
          conda activate env
          pytest -v

      - uses: codecov/codecov-action@v3
        with:
          #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
            #files: ./coverage1.xml,./coverage2.xml # optional
            #flags: unittests # optional
            #name: codecov-umbrella # optional
            #fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
