name: Windows CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@master
        with:
            channels: conda-forge
            python-version: ${{ matrix.python-version }}
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Set up env
        shell: "bash -l {0}"
        run: |
          conda create -n env python==${{matrix.python-version}} wheel pip compilers
          conda activate env
          which pip
          pip install -r requirements_test.txt -r requirements.txt
          conda env export

      - name: Install numcodecs
        shell: "bash -l {0}"
        run: |
          conda activate env
          export CC=clang
          python -m pip install -U pip -r requirements_test.txt -r requirements.txt
          python -m pip install -v -e .

      - name: Run tests
        shell: "bash -l {0}"
        run: |
          conda activate env
          pytest -v --pyargs numcodecs
